# Generated by Django 3.2.9 on 2021-11-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecomodel',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
