# Generated by Django 3.2.9 on 2021-11-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0003_alter_enderecomodel_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecomodel',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='enderecomodel',
            name='numero',
            field=models.CharField(max_length=8),
        ),
    ]
