# Generated by Django 3.2.9 on 2021-11-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='alunomodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
