# Generated by Django 3.2.9 on 2021-11-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20211119_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
