# Generated by Django 3.2.9 on 2021-11-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursomodel',
            name='horas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
